### ISSUE TITLE
Error: Unknown condition: contains name

### ISSUE THREAD

**Issue by eyaladmin** [ceramicskate0/sysmon-config#7]
Hi
it happened when used the sysmon -c "sysmonconfig-export.xml"
on the 21 Feb 2020 release
thanks

**Comment by ceramicskate0** [comment]
Thanks ill look into it today and get back with you

**Comment by ceramicskate0** [comment]
Fix pushed. Plz let me know if this resolves issue for you

**Comment by eyaladmin** [comment]
It's working now

thank you very much 🙂

________________________________
