### ISSUE TITLE
add locations to monitor for writes and dll runs

### ISSUE THREAD

**Issue by ceramic-skate0** [ceramicskate0/sysmon-config#81]
https://helgeklein.com/blog/finding-executables-in-user-writeable-directories/
"C:\Windows\System32\Microsoft\Crypto\RSA\MachineKeys","Everyone",write+read,no_inheritance
"C:\Windows\System32\spool\SERVERS","BUILTIN\Users",FILE_ADD_FILE+FILE_ADD_SUBDIRECTORY+FILE_READ_EA+FILE_READ_ATTRIBUTES,container_inherit
"C:\Windows\System32\Tasks","NT AUTHORITY\Authenticated Users",write+READ_CONTROL,container_inherit

c:\Program Files\Microsoft SQL Server\130\Shared\ErrorDumps
c:\Program Files\ViPER4Windows\DriverComm
c:\Program Files (x86)\Common Files\Adobe\SLCache

**Comment by ceramicskate0** [comment]
file writes covered
