### ISSUE TITLE
The vulnerable driver blocklist after the October 2022 preview release

### ISSUE THREAD

**Issue by ghost** [ceramicskate0/sysmon-config#82]
https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules

**Comment by ceramic-skate0** [comment]
@ceramicskate0

**Comment by ceramicskate0** [comment]
all driver loads captured in config sysmon doesnt block driver loads as of today

**Comment by ceramicskate0** [comment]
adden: most driver loads cpature unless vendor is excluded
